### ISSUE TITLE
你好，请问你用的是什么系统

### ISSUE THREAD

**Issue by yangninghua** [amiltonwong/xl_3d#1]
我的是ubuntu16.04 会遇到，程序能运行，也能出结果，比如特征点检测，最后会有xmk1.sift.png，但是这个图片，并没有把特征画出来，当然，匹配也是一样

**Comment by amiltonwong** [comment]
The same as yours. I use ubuntu 16.04 also. I think perhaps there's some package missing in your system.

**Comment by yangninghua** [comment]
Hamiltonton, thank you for your answer, I forgot that github needs English communication, let more people understand the problem and solve the problem, I will pay attention to it later.

**Comment by yangninghua** [comment]
I installed the following dependencies
Sudo apt-get install libjpeg-dev libpng-dev libtiff-dev
Sudo apt-get install libeigen3-dev

**Comment by yangninghua** [comment]
![image](https://user-images.githubusercontent.com/32252319/47958843-0eaab580-e00f-11e8-9452-e6f00ab6f18b.png)
![image](https://user-images.githubusercontent.com/32252319/47958846-19fde100-e00f-11e8-8296-bbdc56637a39.png)
